### ISSUE TITLE
ArgumentError: wrong number of arguments (given 1, expected 0)

### ISSUE THREAD

**Issue by dorijan** [nerdgeschoss/pixelpress#20]
Hi,
I was trying to use this gem, followed readme, but got this error when I try to run `InvoicePrinter.customer_invoice.pdf`

This is the error in the console:

```
Running via Spring preloader in process 3031238
Loading development environment (Rails 5.0.7.2)
irb(main):001:0> InvoicePrinter.customer_invoice.pdf
ArgumentError: wrong number of arguments (given 1, expected 0)
        from /home/dorijan/ruby/potrcko/app/printers/invoice_printer.rb:2:in `customer_invoice'
        from /home/dorijan/.rbenv/versions/2.4.10/lib/ruby/gems/2.4.0/gems/pixelpress-0.2.3/lib/pixelpress/instance_invocation.rb:7:in `method_missing'
        from (irb):1
        from /home/dorijan/.rbenv/versions/2.4.10/lib/ruby/gems/2.4.0/gems/railties-5.0.7.2/lib/rails/commands/console.rb:65:in `start'
        from /home/dorijan/.rbenv/versions/2.4.10/lib/ruby/gems/2.4.0/gems/railties-5.0.7.2/lib/rails/commands/console_helper.rb:9:in `start'
        from /home/dorijan/.rbenv/versions/2.4.10/lib/ruby/gems/2.4.0/gems/railties-5.0.7.2/lib/rails/commands/commands_tasks.rb:78:in `console'
        from /home/dorijan/.rbenv/versions/2.4.10/lib/ruby/gems/2.4.0/gems/railties-5.0.7.2/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
        from /home/dorijan/.rbenv/versions/2.4.10/lib/ruby/gems/2.4.0/gems/railties-5.0.7.2/lib/rails/commands.rb:18:in `<top (required)>'
        from /home/dorijan/.rbenv/versions/2.4.10/lib/ruby/gems/2.4.0/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:293:in `require'
        from /home/dorijan/.rbenv/versions/2.4.10/lib/ruby/gems/2.4.0/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:293:in `block in require'
        from /home/dorijan/.rbenv/versions/2.4.10/lib/ruby/gems/2.4.0/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:259:in `load_dependency'
        from /home/dorijan/.rbenv/versions/2.4.10/lib/ruby/gems/2.4.0/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:293:in `require'
        from /home/dorijan/ruby/potrcko/bin/rails:9:in `<top (required)>'
        from /home/dorijan/.rbenv/versions/2.4.10/lib/ruby/gems/2.4.0/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:287:in `load'
        from /home/dorijan/.rbenv/versions/2.4.10/lib/ruby/gems/2.4.0/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:287:in `block in load'
        from /home/dorijan/.rbenv/versions/2.4.10/lib/ruby/gems/2.4.0/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:259:in `load_dependency'
        from /home/dorijan/.rbenv/versions/2.4.10/lib/ruby/gems/2.4.0/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:287:in `load'
        from /home/dorijan/.rbenv/versions/2.4.10/lib/ruby/gems/2.4.0/gems/spring-2.1.1/lib/spring/commands/rails.rb:6:in `call'
        from /home/dorijan/.rbenv/versions/2.4.10/lib/ruby/gems/2.4.0/gems/spring-2.1.1/lib/spring/command_wrapper.rb:38:in `call'
        from /home/dorijan/.rbenv/versions/2.4.10/lib/ruby/gems/2.4.0/gems/spring-2.1.1/lib/spring/application.rb:220:in `block in serve'
        from /home/dorijan/.rbenv/versions/2.4.10/lib/ruby/gems/2.4.0/gems/spring-2.1.1/lib/spring/application.rb:180:in `fork'
        from /home/dorijan/.rbenv/versions/2.4.10/lib/ruby/gems/2.4.0/gems/spring-2.1.1/lib/spring/application.rb:180:in `serve'
        from /home/dorijan/.rbenv/versions/2.4.10/lib/ruby/gems/2.4.0/gems/spring-2.1.1/lib/spring/application.rb:145:in `block in run'
        from /home/dorijan/.rbenv/versions/2.4.10/lib/ruby/gems/2.4.0/gems/spring-2.1.1/lib/spring/application.rb:139:in `loop'
        from /home/dorijan/.rbenv/versions/2.4.10/lib/ruby/gems/2.4.0/gems/spring-2.1.1/lib/spring/application.rb:139:in `run'
        from /home/dorijan/.rbenv/versions/2.4.10/lib/ruby/gems/2.4.0/gems/spring-2.1.1/lib/spring/application/boot.rb:19:in `<top (required)>'
        from /home/dorijan/.rbenv/versions/2.4.10/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:85:in `require'
        from /home/dorijan/.rbenv/versions/2.4.10/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:85:in `require'
        from -e:1:in `<main>'

```

**Comment by Adeynack** [comment]
Hello @dorijan and thanks for reporting this. Are you using Ruby 3 or Ruby 2? We did a change lately for Ruby 3 changes in argument passing in #18.

**Comment by dorijan** [comment]
Great, thank you very much

**Comment by JensRavens** [comment]
Just jumping in here: You're using ruby 2.4 which had its end of life [almost 3 years ago](https://endoflife.date/ruby). That version doesn't support some language features (keyword arguments) that are used in this code base, that's why you're getting this error.

What you can do about it:
- upgrade to at least ruby 2.7 (which will also EOL in 4 weeks) or better ruby 3 - it's a good investment into the security of your app
- downgrade pixelpress to an earlier version (I'm not sure which old version still supports ruby 2.4)
